In [ ]:
sample_response = {
    "account_holder": "Priya Sharma",
    "account_number": "1234567890",
    "balance": 45230.50,
    "currency": "INR",
    "is_active": True
}

print(sample_response["account_holder"])
print(sample_response["balance"])

Priya Sharma
45230.5

In [ ]:
# Real responses have nested structures
transaction_response = {

    "account": {
        "holder_name": "Priya Sharma",
        "number": "1234567890"
    },

    "transactions": [
        {"date": "2024-01-15", "amount": -500, "merchant": "Swiggy"},
        {"date": "2024-01-14", "amount": -1200, "merchant": "Amazon"},
        {"date": "2024-01-13", "amount": 50000, "merchant": "Salary Credit"}
    ],
    "meta": {
        "total_transactions": 3,
        "request_time": "2024-01-16T10:30:00"
    }
}

print(transaction_response["account"]["holder_name"])

print(transaction_response["transactions"][0])

print(transaction_response["transactions"][1]["merchant"])

Priya Sharma
{'date': '2024-01-15', 'amount': -500, 'merchant': 'Swiggy'}
Amazon

In [ ]:
data = {
    "name" : "Rahul",
    "age" : 20,
    "marks" : [10,20,30],
    "hobbies" : {
                   "first": "football",
                   "second" : "badminton"
                }
}

print(data["marks"][1])
print(data["hobbies"]["second"])

20
badminton

In [ ]:
import requests
import json

# Step 1: Define where we're calling (the endpoint)
url = "https://jsonplaceholder.typicode.com/users"

# Step 2: Make the request
response = requests.get(url)

print(response.status_code)

print(response.json())

200
[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

In [ ]:
data = response.json()

print(data)

[{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}, {'id': 2, 'name': 'Ervin Howell', 'username': 'Antonette', 'email': 'Shanna@melissa.tv', 'address': {'street': 'Victor Plains', 'suite': 'Suite 879', 'city': 'Wisokyburgh', 'zipcode': '90566-7771', 'geo': {'lat': '-43.9509', 'lng': '-34.4618'}}, 'phone': '010-692-6593 x09125', 'website': 'anastasia.net', 'company': {'name': 'Deckow-Crist', 'catchPhrase': 'Proactive didactic contingency', 'bs': 'synergize scalable supply-chains'}}, {'id': 3, 'name': 'Clementine Bauch', 'username': 'Samantha', 'email': 'Nathan@yesenia.net', 'address': {'street': 'Douglas Extension', 'suite': 'Suite 847', 'city': 'McKenziehaven', 'zipcode': '59590-4157', 'geo': {'lat': '-68.6102', 'lng': '-47.0653'}}, 'phone': '1-463-123-4447', 'website': 'ramiro.info', 'company': {'name': 'Romaguera-Jacobson', 'catchPhrase': 'Face to face bifurcated interface', 'bs': 'e-enable strategic applications'}}, {'id': 4, 'name': 'Patricia Lebsack', 'username': 'Karianne', 'email': 'Julianne.OConner@kory.org', 'address': {'street': 'Hoeger Mall', 'suite': 'Apt. 692', 'city': 'South Elvis', 'zipcode': '53919-4257', 'geo': {'lat': '29.4572', 'lng': '-164.2990'}}, 'phone': '493-170-9623 x156', 'website': 'kale.biz', 'company': {'name': 'Robel-Corkery', 'catchPhrase': 'Multi-tiered zero tolerance productivity', 'bs': 'transition cutting-edge web services'}}, {'id': 5, 'name': 'Chelsey Dietrich', 'username': 'Kamren', 'email': 'Lucio_Hettinger@annie.ca', 'address': {'street': 'Skiles Walks', 'suite': 'Suite 351', 'city': 'Roscoeview', 'zipcode': '33263', 'geo': {'lat': '-31.8129', 'lng': '62.5342'}}, 'phone': '(254)954-1289', 'website': 'demarco.info', 'company': {'name': 'Keebler LLC', 'catchPhrase': 'User-centric fault-tolerant solution', 'bs': 'revolutionize end-to-end systems'}}, {'id': 6, 'name': 'Mrs. Dennis Schulist', 'username': 'Leopoldo_Corkery', 'email': 'Karley_Dach@jasper.info', 'address': {'street': 'Norberto Crossing', 'suite': 'Apt. 950', 'city': 'South Christy', 'zipcode': '23505-1337', 'geo': {'lat': '-71.4197', 'lng': '71.7478'}}, 'phone': '1-477-935-8478 x6430', 'website': 'ola.org', 'company': {'name': 'Considine-Lockman', 'catchPhrase': 'Synchronised bottom-line interface', 'bs': 'e-enable innovative applications'}}, {'id': 7, 'name': 'Kurtis Weissnat', 'username': 'Elwyn.Skiles', 'email': 'Telly.Hoeger@billy.biz', 'address': {'street': 'Rex Trail', 'suite': 'Suite 280', 'city': 'Howemouth', 'zipcode': '58804-1099', 'geo': {'lat': '24.8918', 'lng': '21.8984'}}, 'phone': '210.067.6132', 'website': 'elvis.io', 'company': {'name': 'Johns Group', 'catchPhrase': 'Configurable multimedia task-force', 'bs': 'generate enterprise e-tailers'}}, {'id': 8, 'name': 'Nicholas Runolfsdottir V', 'username': 'Maxime_Nienow', 'email': 'Sherwood@rosamond.me', 'address': {'street': 'Ellsworth Summit', 'suite': 'Suite 729', 'city': 'Aliyaview', 'zipcode': '45169', 'geo': {'lat': '-14.3990', 'lng': '-120.7677'}}, 'phone': '586.493.6943 x140', 'website': 'jacynthe.com', 'company': {'name': 'Abernathy Group', 'catchPhrase': 'Implemented secondary concept', 'bs': 'e-enable extensible e-tailers'}}, {'id': 9, 'name': 'Glenna Reichert', 'username': 'Delphine', 'email': 'Chaim_McDermott@dana.io', 'address': {'street': 'Dayna Park', 'suite': 'Suite 449', 'city': 'Bartholomebury', 'zipcode': '76495-3109', 'geo': {'lat': '24.6463', 'lng': '-168.8889'}}, 'phone': '(775)976-6794 x41206', 'website': 'conrad.com', 'company': {'name': 'Yost and Sons', 'catchPhrase': 'Switchable contextually-based project', 'bs': 'aggregate real-time technologies'}}, {'id': 10, 'name': 'Clementina DuBuque', 'username': 'Moriah.Stanton', 'email': 'Rey.Padberg@karina.biz', 'address': {'street': 'Kattie Turnpike', 'suite': 'Suite 198', 'city': 'Lebsackbury', 'zipcode': '31428-2261', 'geo': {'lat': '-38.2386', 'lng': '57.2232'}}, 'phone': '024-648-3804', 'website': 'ambrose.net', 'company': {'name': 'Hoeger LLC', 'catchPhrase': 'Centralized empowering task-force', 'bs': 'target end-to-end models'}}]

In [ ]:
# Pretty print for readability

print(json.dumps(data, indent=2))

[
  {
    "id": 1,
    "name": "Leanne Graham",
    "username": "Bret",
    "email": "Sincere@april.biz",
    "address": {
      "street": "Kulas Light",
      "suite": "Apt. 556",
      "city": "Gwenborough",
      "zipcode": "92998-3874",
      "geo": {
        "lat": "-37.3159",
        "lng": "81.1496"
      }
    },
    "phone": "1-770-736-8031 x56442",
    "website": "hildegard.org",
    "company": {
      "name": "Romaguera-Crona",
      "catchPhrase": "Multi-layered client-server neural-net",
      "bs": "harness real-time e-markets"
    }
  },
  {
    "id": 2,
    "name": "Ervin Howell",
    "username": "Antonette",
    "email": "Shanna@melissa.tv",
    "address": {
      "street": "Victor Plains",
      "suite": "Suite 879",
      "city": "Wisokyburgh",
      "zipcode": "90566-7771",
      "geo": {
        "lat": "-43.9509",
        "lng": "-34.4618"
      }
    },
    "phone": "010-692-6593 x09125",
    "website": "anastasia.net",
    "company": {
      "name": "Deckow-Crist",
      "catchPhrase": "Proactive didactic contingency",
      "bs": "synergize scalable supply-chains"
    }
  },
  {
    "id": 3,
    "name": "Clementine Bauch",
    "username": "Samantha",
    "email": "Nathan@yesenia.net",
    "address": {
      "street": "Douglas Extension",
      "suite": "Suite 847",
      "city": "McKenziehaven",
      "zipcode": "59590-4157",
      "geo": {
        "lat": "-68.6102",
        "lng": "-47.0653"
      }
    },
    "phone": "1-463-123-4447",
    "website": "ramiro.info",
    "company": {
      "name": "Romaguera-Jacobson",
      "catchPhrase": "Face to face bifurcated interface",
      "bs": "e-enable strategic applications"
    }
  },
  {
    "id": 4,
    "name": "Patricia Lebsack",
    "username": "Karianne",
    "email": "Julianne.OConner@kory.org",
    "address": {
      "street": "Hoeger Mall",
      "suite": "Apt. 692",
      "city": "South Elvis",
      "zipcode": "53919-4257",
      "geo": {
        "lat": "29.4572",
        "lng": "-164.2990"
      }
    },
    "phone": "493-170-9623 x156",
    "website": "kale.biz",
    "company": {
      "name": "Robel-Corkery",
      "catchPhrase": "Multi-tiered zero tolerance productivity",
      "bs": "transition cutting-edge web services"
    }
  },
  {
    "id": 5,
    "name": "Chelsey Dietrich",
    "username": "Kamren",
    "email": "Lucio_Hettinger@annie.ca",
    "address": {
      "street": "Skiles Walks",
      "suite": "Suite 351",
      "city": "Roscoeview",
      "zipcode": "33263",
      "geo": {
        "lat": "-31.8129",
        "lng": "62.5342"
      }
    },
    "phone": "(254)954-1289",
    "website": "demarco.info",
    "company": {
      "name": "Keebler LLC",
      "catchPhrase": "User-centric fault-tolerant solution",
      "bs": "revolutionize end-to-end systems"
    }
  },
  {
    "id": 6,
    "name": "Mrs. Dennis Schulist",
    "username": "Leopoldo_Corkery",
    "email": "Karley_Dach@jasper.info",
    "address": {
      "street": "Norberto Crossing",
      "suite": "Apt. 950",
      "city": "South Christy",
      "zipcode": "23505-1337",
      "geo": {
        "lat": "-71.4197",
        "lng": "71.7478"
      }
    },
    "phone": "1-477-935-8478 x6430",
    "website": "ola.org",
    "company": {
      "name": "Considine-Lockman",
      "catchPhrase": "Synchronised bottom-line interface",
      "bs": "e-enable innovative applications"
    }
  },
  {
    "id": 7,
    "name": "Kurtis Weissnat",
    "username": "Elwyn.Skiles",
    "email": "Telly.Hoeger@billy.biz",
    "address": {
      "street": "Rex Trail",
      "suite": "Suite 280",
      "city": "Howemouth",
      "zipcode": "58804-1099",
      "geo": {
        "lat": "24.8918",
        "lng": "21.8984"
      }
    },
    "phone": "210.067.6132",
    "website": "elvis.io",
    "company": {
      "name": "Johns Group",
      "catchPhrase": "Configurable multimedia task-force",
      "bs": "generate enterprise e-tailers"
    }
  },
  {
    "id": 8,
    "name": "Nicholas Runolfsdottir V",
    "username": "Maxime_Nienow",
    "email": "Sherwood@rosamond.me",
    "address": {
      "street": "Ellsworth Summit",
      "suite": "Suite 729",
      "city": "Aliyaview",
      "zipcode": "45169",
      "geo": {
        "lat": "-14.3990",
        "lng": "-120.7677"
      }
    },
    "phone": "586.493.6943 x140",
    "website": "jacynthe.com",
    "company": {
      "name": "Abernathy Group",
      "catchPhrase": "Implemented secondary concept",
      "bs": "e-enable extensible e-tailers"
    }
  },
  {
    "id": 9,
    "name": "Glenna Reichert",
    "username": "Delphine",
    "email": "Chaim_McDermott@dana.io",
    "address": {
      "street": "Dayna Park",
      "suite": "Suite 449",
      "city": "Bartholomebury",
      "zipcode": "76495-3109",
      "geo": {
        "lat": "24.6463",
        "lng": "-168.8889"
      }
    },
    "phone": "(775)976-6794 x41206",
    "website": "conrad.com",
    "company": {
      "name": "Yost and Sons",
      "catchPhrase": "Switchable contextually-based project",
      "bs": "aggregate real-time technologies"
    }
  },
  {
    "id": 10,
    "name": "Clementina DuBuque",
    "username": "Moriah.Stanton",
    "email": "Rey.Padberg@karina.biz",
    "address": {
      "street": "Kattie Turnpike",
      "suite": "Suite 198",
      "city": "Lebsackbury",
      "zipcode": "31428-2261",
      "geo": {
        "lat": "-38.2386",
        "lng": "57.2232"
      }
    },
    "phone": "024-648-3804",
    "website": "ambrose.net",
    "company": {
      "name": "Hoeger LLC",
      "catchPhrase": "Centralized empowering task-force",
      "bs": "target end-to-end models"
    }
  }
]

In [ ]:
# print(json.dumps(data[0], indent=2))

print(data[0]["username"])

Bret

In [ ]:
import requests
import json

# Step 1: Define where we're calling (the endpoint)
url = "https://jsonplaceholder.typicode.com/users/1"

# Step 2: Make the request
response = requests.get(url)

print(response.status_code)

data = response.json()

print(json.dumps(data, indent=2))

200
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
    }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
}

In [ ]:
# Step 1: Define where we're calling (the endpoint)
url = "https://jsonplaceholder.typicode.com/users/1"

# Step 2: Make the request
response = requests.get(url)

# Step 3: Check if it worked
print("Status Code:", response.status_code)
# 200 = Success, 404 = Not Found, 401 = Unauthorized, 500 = Server Error

# Step 4: Extract the data (JSON)
data = response.json()

# Step 5: Look at it
print(data)

Status Code: 200
{'id': 1, 'name': 'Leanne Graham', 'username': 'Bret', 'email': 'Sincere@april.biz', 'address': {'street': 'Kulas Light', 'suite': 'Apt. 556', 'city': 'Gwenborough', 'zipcode': '92998-3874', 'geo': {'lat': '-37.3159', 'lng': '81.1496'}}, 'phone': '1-770-736-8031 x56442', 'website': 'hildegard.org', 'company': {'name': 'Romaguera-Crona', 'catchPhrase': 'Multi-layered client-server neural-net', 'bs': 'harness real-time e-markets'}}

In [ ]:
# Step 1: Define where we're calling (the endpoint)
url = "https://jsonplaceholder.typicode.com/users"

# Step 2: Make the request
response = requests.get(url)

# Step 3: Check if it worked
print("Status Code:", response.status_code)
# 200 = Success, 404 = Not Found, 401 = Unauthorized, 500 = Server Error

# Step 4: Extract the data (JSON)
data = response.json()



# How many?
print(f"Total users: {len(data)}")


# Look at the first one
print(json.dumps(data[0], indent=2))

Status Code: 200
Total users: 10
{
  "id": 1,
  "name": "Leanne Graham",
  "username": "Bret",
  "email": "Sincere@april.biz",
  "address": {
    "street": "Kulas Light",
    "suite": "Apt. 556",
    "city": "Gwenborough",
    "zipcode": "92998-3874",
    "geo": {
      "lat": "-37.3159",
      "lng": "81.1496"
    }
  },
  "phone": "1-770-736-8031 x56442",
  "website": "hildegard.org",
  "company": {
    "name": "Romaguera-Crona",
    "catchPhrase": "Multi-layered client-server neural-net",
    "bs": "harness real-time e-markets"
  }
}

In [ ]:
for user in data:
  print(f"{user["name"]} | {user['email']} | {user['address']['city']}")

Leanne Graham | Sincere@april.biz | Gwenborough
Ervin Howell | Shanna@melissa.tv | Wisokyburgh
Clementine Bauch | Nathan@yesenia.net | McKenziehaven
Patricia Lebsack | Julianne.OConner@kory.org | South Elvis
Chelsey Dietrich | Lucio_Hettinger@annie.ca | Roscoeview
Mrs. Dennis Schulist | Karley_Dach@jasper.info | South Christy
Kurtis Weissnat | Telly.Hoeger@billy.biz | Howemouth
Nicholas Runolfsdottir V | Sherwood@rosamond.me | Aliyaview
Glenna Reichert | Chaim_McDermott@dana.io | Bartholomebury
Clementina DuBuque | Rey.Padberg@karina.biz | Lebsackbury

In [ ]:
# Step 1: Define where we're calling (the endpoint)
url = "https://jsonplaceholder.typicode.com/users"

# Step 2: Make the request
response = requests.get(url)

# Step 3: Check if it worked
print("Status Code:", response.status_code)
# 200 = Success, 404 = Not Found, 401 = Unauthorized, 500 = Server Error

# Step 4: Extract the data (JSON)
data = response.json()

In [ ]:
import pandas as pd

df = pd.DataFrame(data)
df.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [ ]:
# Method 1 : json_normalize - flatten nested structure

from pandas import json_normalize

df_flat = json_normalize(data)
df_flat.head()

,id,name,username,email,phone,website,address.street,address.suite,address.city,address.zipcode,address.geo.lat,address.geo.lng,company.name,company.catchPhrase,company.bs
0,1,Leanne Graham,Bret,Sincere@april.biz,1-770-736-8031 x56442,hildegard.org,Kulas Light,Apt. 556,Gwenborough,92998-3874,-37.3159,81.1496,Romaguera-Crona,Multi-layered client-server neural-net,harness real-time e-markets
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,010-692-6593 x09125,anastasia.net,Victor Plains,Suite 879,Wisokyburgh,90566-7771,-43.9509,-34.4618,Deckow-Crist,Proactive didactic contingency,synergize scalable supply-chains
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,1-463-123-4447,ramiro.info,Douglas Extension,Suite 847,McKenziehaven,59590-4157,-68.6102,-47.0653,Romaguera-Jacobson,Face to face bifurcated interface,e-enable strategic applications
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,493-170-9623 x156,kale.biz,Hoeger Mall,Apt. 692,South Elvis,53919-4257,29.4572,-164.2990,Robel-Corkery,Multi-tiered zero tolerance productivity,transition cutting-edge web services
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,(254)954-1289,demarco.info,Skiles Walks,Suite 351,Roscoeview,33263,-31.8129,62.5342,Keebler LLC,User-centric fault-tolerant solution,revolutionize end-to-end systems

In [ ]:
print(df_flat.columns.tolist())

['id', 'name', 'username', 'email', 'phone', 'website', 'address.street', 'address.suite', 'address.city', 'address.zipcode', 'address.geo.lat', 'address.geo.lng', 'company.name', 'company.catchPhrase', 'company.bs']

In [ ]:
df_clean = df_flat[['id', 'name', 'email', 'phone', 'address.city', 'company.name']]

# rename
df_clean.columns = ['user_id', 'name', 'email', 'phone', 'city', 'company']

df_clean.head()

,user_id,name,email,phone,city,company
0,1,Leanne Graham,Sincere@april.biz,1-770-736-8031 x56442,Gwenborough,Romaguera-Crona
1,2,Ervin Howell,Shanna@melissa.tv,010-692-6593 x09125,Wisokyburgh,Deckow-Crist
2,3,Clementine Bauch,Nathan@yesenia.net,1-463-123-4447,McKenziehaven,Romaguera-Jacobson
3,4,Patricia Lebsack,Julianne.OConner@kory.org,493-170-9623 x156,South Elvis,Robel-Corkery
4,5,Chelsey Dietrich,Lucio_Hettinger@annie.ca,(254)954-1289,Roscoeview,Keebler LLC

In [ ]:
# Simulated payment gateway response (like Razorpay or Stripe)
payment_data = {
    "payments": [
        {
            "payment_id": "pay_ABC123",
            "amount": 1500,
            "currency": "INR",
            "status": "captured",
            "method": "upi",
            "customer": {
                "id": "cust_001",
                "email": "priya@email.com",
                "contact": "9876543210"
            },
            "upi": {
                "vpa": "priya@okaxis"
            },
            "created_at": 1705320000
        },
        {
            "payment_id": "pay_DEF456",
            "amount": 3200,
            "currency": "INR",
            "status": "captured",
            "method": "card",
            "customer": {
                "id": "cust_002",
                "email": "rahul@email.com",
                "contact": "9876543211"
            },
            "card": {
                "last4": "4242",
                "network": "Visa"
            },
            "created_at": 1705406400
        }
    ],
    "count": 2,
    "has_more": False
}

In [ ]:
payments_list = payment_data["payments"]

df_payments = json_normalize(payments_list)

print(df_payments.head())

   payment_id  amount currency    status method  created_at customer.id  \
0  pay_ABC123    1500      INR  captured    upi  1705320000    cust_001
1  pay_DEF456    3200      INR  captured   card  1705406400    cust_002

    customer.email customer.contact       upi.vpa card.last4 card.network
0  priya@email.com       9876543210  priya@okaxis        NaN          NaN
1  rahul@email.com       9876543211           NaN       4242         Visa

In [ ]:
print(df_payments.columns.tolist())

['payment_id', 'amount', 'currency', 'status', 'method', 'created_at', 'customer.id', 'customer.email', 'customer.contact', 'upi.vpa', 'card.last4', 'card.network']

In [ ]:
# Step 3: Select and clean
df_payments_clean = df_payments[[ 'payment_id', 'amount', 'status', 'method','customer.email', 'created_at']].copy()

# Rename

df_payments_clean.columns = [ 'payment_id', 'amount', 'status', 'method','customer_email', 'timestamp']

df_payments_clean

   payment_id  amount    status method   customer_email   timestamp
0  pay_ABC123    1500  captured    upi  priya@email.com  1705320000
1  pay_DEF456    3200  captured   card  rahul@email.com  1705406400

In [ ]:
df_payments_clean['timestamp'] = pd.to_datetime(
                                   df_payments_clean['timestamp'], unit='s'
                                )

df_payments_clean

   payment_id  amount    status method   customer_email           timestamp
0  pay_ABC123    1500  captured    upi  priya@email.com 2024-01-15 12:00:00
1  pay_DEF456    3200  captured   card  rahul@email.com 2024-01-16 12:00:00

In [ ]:
# Get 30 days of Bitcoin price history

url_history = "https://api.coingecko.com/api/v3/coins/bitcoin/market_chart"

params = {
    "vs_currency": "inr",
    "days": "30",
    "interval": "daily"
}

response = requests.get(url_history, params=params)

history_data = response.json()

history_data

{'prices': [[1772496000000, 6305544.630558076],
  [1772582400000, 6286193.4883730775],
  [1772668800000, 6694568.0647264635],
  [1772755200000, 6505413.051213356],
  [1772841600000, 6265583.842492761],
  [1772928000000, 6184943.552139279],
  [1773014400000, 6071162.609842083],
  [1773100800000, 6319544.712079575],
  [1773187200000, 6427459.132593709],
  [1773273600000, 6476952.781587672],
  [1773360000000, 6517601.8570237355],
  [1773446400000, 6571729.3213031115],
  [1773532800000, 6593624.616147389],
  [1773619200000, 6727548.65801573],
  [1773705600000, 6906940.623961062],
  [1773792000000, 6829860.404015485],
  [1773878400000, 6639390.135900453],
  [1773964800000, 6504037.303025701],
  [1774051200000, 6635372.108167125],
  [1774137600000, 6461678.631620447],
  [1774224000000, 6364717.089252187],
  [1774310400000, 6614293.785503927],
  [1774396800000, 6649392.307315811],
  [1774483200000, 6712173.7324164715],
  [1774569600000, 6487672.4747853875],
  [1774656000000, 6291490.149056623],
  [1774742400000, 6286074.723243884],
  [1774828800000, 6252812.76341992],
  [1774915200000, 6293233.346703139],
  [1775001600000, 6378628.7912758235],
  [1775059422000, 6415080.84974683]],
 'market_caps': [[1772496000000, 126152757006839.64],
  [1772582400000, 125797160464755.47],
  [1772668800000, 133863225754594.66],
  [1772755200000, 130122238295766.53],
  [1772841600000, 125413568438094.62],
  [1772928000000, 123666079387081.88],
  [1773014400000, 121505932083664.62],
  [1773100800000, 126461917417352.53],
  [1773187200000, 128535957968684.31],
  [1773273600000, 129602949307984.31],
  [1773360000000, 130400517435625.14],
  [1773446400000, 131418637580909.56],
  [1773532800000, 131902522403127.42],
  [1773619200000, 134567700491129.14],
  [1773705600000, 138087508471241.77],
  [1773792000000, 136644214839023.36],
  [1773878400000, 132800021801943.4],
  [1773964800000, 130053131197903.89],
  [1774051200000, 132754540593305.97],
  [1774137600000, 129859086038431.03],
  [1774224000000, 127317118702167.67],
  [1774310400000, 132291904081707.83],
  [1774396800000, 133021964277040.81],
  [1774483200000, 134294020803557.73],
  [1774569600000, 129766811172427.31],
  [1774656000000, 125800402010145.08],
  [1774742400000, 125774289084510.89],
  [1774828800000, 125118807122886.17],
  [1774915200000, 125916761150125.12],
  [1775001600000, 127579123373519.0],
  [1775059422000, 128477617058535.72]],
 'total_volumes': [[1772496000000, 5585066997756.818],
  [1772582400000, 4849238095131.352],
  [1772668800000, 7469488758107.77],
  [1772755200000, 5077047821294.556],
  [1772841600000, 4268610743196.183],
  [1772928000000, 2260709884906.4233],
  [1773014400000, 3295558377635.807],
  [1773100800000, 4838898391541.992],
  [1773187200000, 5245430618373.838],
  [1773273600000, 4444396297119.903],
  [1773360000000, 3981398489566.5166],
  [1773446400000, 5771898947808.115],
  [1773532800000, 2200166136169.016],
  [1773619200000, 2696984552297.951],
  [1773705600000, 5206137869098.035],
  [1773792000000, 4415764576262.512],
  [1773878400000, 4308063452922.2896],
  [1773964800000, 4288415087076.7983],
  [1774051200000, 3695027863223.9507],
  [1774137600000, 2142317322254.7058],
  [1774224000000, 2849883631012.316],
  [1774310400000, 4898499562479.861],
  [1774396800000, 3808643391622.7354],
  [1774483200000, 3441912199405.2896],
  [1774569600000, 4926242344811.966],
  [1774656000000, 4636433359009.785],
  [1774742400000, 2240384294593.629],
  [1774828800000, 2378599624182.63],
  [1774915200000, 3500329121155.635],
  [1775001600000, 5254840222309.1045],
  [1775059422000, 5106120681383.758]]}

In [ ]:
print(history_data.keys())

dict_keys(['prices', 'market_caps', 'total_volumes'])